version: '3'

networks:
  laravel:
    driver: bridge

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: tsa_nginx
    ports:
      - "127.0.0.1:8029:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: tsa_db
    ports:
      - "127.0.0.1:3029:3306"
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
      MYSQL_DATABASE: payment_db
      MYSQL_USER: payment_user
      MYSQL_PASSWORD: topsecret
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: tsa_php
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "127.0.0.1:9029:9000"
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: tsa_artisan
    volumes:
      - ./src:/var/www/html:delegated
    working_dir: /var/www/html
    depends_on:
      - db
    user: laravel
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel